on: 
  push: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: action/checkout@v3

      - name: 'login'
       run: docker login --username ${{ secrets.Username}} --password ${{ secrets.Password}}

      - name: 'build image'
        run: docker build -t ${{ secrets.Username}}/my-image

      - name: 'push docker image'
        run: docker push ${{ secrets.Username}}/my-image    